# Controls When Workflow Will Run
on:
  # Triggers on push/pull, only for specified branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to manually run workflow from Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be exectued as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
